version: '3.9'
services:
  db:
    image: mariadb:10.7.3-focal
    restart: on-failure
    ports:
      - '3306:3306'
    env_file: 
      - .env
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
  nginx:
    image: nginx:1.21.6-alpine
    restart: on-failure
    volumes: 
      - './app/public:/usr/src/app/public'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
    ports:
      - '127.0.0.1:80:80'
  php: 
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './app:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    user: 1000:1000
