api_get_products:
    path: /products
    controller: App\Controller\ProductController::listAllProducts
    methods: GET

api_get_one_product:
    path: /products/{id}
    controller: App\Controller\ProductController::getOneProduct

api_get_customers_from_partner:
    path: /partners/{id}/customers
    controller: App\Controller\PartnerController::getAllCustomersFromPartner

# api_get_customer_from_partner:
#     path: /partner/{id}/customers/{id}
#     controller: App\Controller\PartnerController::getOneCustomerFromPartner

kernel:
    resource: ../src/Kernel.php
    type: annotation
