api_get_products:
    path: /api/products
    controller: App\Controller\ProductController::listAllProducts
    methods: GET

api_get_one_product:
    path: /api/products/{id}
    controller: App\Controller\ProductController::getOneProduct
    methods: GET

api_get_customers_from_partner:
    path: /api/partners/{id}/customers
    controller: App\Controller\PartnerController::getAllCustomersFromPartner
    methods: GET

api_get_customer_from_partner:
    path: /api/partners/{partnerId}/customers/{customerId}
    controller: App\Controller\PartnerController::getOneCustomerFromPartner
    methods: GET

api_create_new_user:
    path: /api/customers/new
    controller: App\Controller\CustomerController::createCustomer
    methods: POST

api_delete_customer:
    path: /api/partners/{partnerId}/customers/{customerId}/delete
    controller: App\Controller\CustomerController::deleteCustomer
    methods: DELETE

api_login_check:
    path: /api/login_check

kernel:
    resource: ../src/Kernel.php
    type: annotation
